# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "My eval"

prompts:
  - prompt.yaml
providers:
  - openai:gpt-4o-mini
  # - openai:chat:gpt-4o-mini

defaultTest:
  options:
    provider: openai:gpt-4o-mini

tests:
  - vars:
      # NOTE: Tokens: 48,607
      diffs: 'file://test-files/langfuse/langfuse/pr-5672/diffs.txt'
      before_schema: 'file://test-files/langfuse/langfuse/pr-5672/before_schema.txt'
    assert:
      - type: cost
        threshold: 0.008

  - vars:
      # NOTE: Tokens: 12,274
      diffs: 'file://test-files/langfuse/langfuse/pr-4946/diffs.txt'
      before_schema: 'file://test-files/langfuse/langfuse/pr-4946/before_schema.txt'
    assert:
      - type: llm-rubric
        value: 'The report evaluates the **risk of data loss**.'
      - type: cost
        threshold: 0.008
