name: pnpm-setup

inputs:
  working-directory:
    required: false
    type: string
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
      with:
        package_json_file: ${{ inputs.working-directory }}/package.json
    - name: Setup node env
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
      working-directory: ${{ inputs.working-directory }}
