name: "Deploy App"

inputs:
  app-name:
    required: true
    type: string
  environment:
    required: true
    type: string
  vercel-project-id-key:
    required: true
    type: string
  vercel-token:
    required: true
    type: string
outputs:
  deployment-url:
    value: ${{ steps.deployment.outputs.deployment-url }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: ./.github/actions/pnpm-setup
    - name: List files
      run: ls -R
      shell: bash
    - name: Install Vercel CLI
      run: pnpm add --global vercel@latest
      shell: bash
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ inputs.vercel-token }}
      shell: bash
    - name: Run prepare command
      run: pnpm build
      shell: bash
    - name: Update index.html content
      run: pnpm --filter ${{ inputs.app-name }} update_dist_content
      shell: bash
    - name: Find all public directories and check permissions
      run: |
        find . -type d -name 'public' -exec ls -ld {} \;
      shell: bash
    - name: Build Project Artifacts
      run: vercel build ${{ inputs.environment == 'production' && '--prod' || '' }}
      shell: bash
    - name: Deploy Project Artifacts to Vercel
      id: deployment
      run: |
        vercel deploy --prebuilt --token=${{ inputs.vercel-token }} ${{ inputs.environment == 'production' && '--prod' || '' }} > deployment-url.txt
        echo "deployment-url=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
      shell: bash
