name: Claude Code Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-review:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Claude Code Security Review
        uses: anthropics/claude-code-security-review@c19afa74097b892109a6598b94297280ce7d1beb
        with:
          claude-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          comment-pr: true
          upload-results: true
          exclude-directories: 'node_modules,dist,build,.next'
          claudecode-timeout: 20
