name: E2E Tests
on:
  workflow_run:
    workflows:
      - "Vercel Deployment"
      - "Vercel Deployment erd-sample"
    types:
      - completed

env:
  CI: true
  WORKING_DIRECTORY: .

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-deployment-outputs:
    runs-on: ubuntu-latest
    outputs:
      erd-web-url: ${{ steps.set-env.outputs.erd-web-url }}
      cli-url: ${{ steps.set-env.outputs.cli-url }}
    steps:
      - name: Get deployment outputs
        id: set-env
        run: |
          DEPLOYMENT_RUN_ID=${{ github.event.workflow_run.id }}
          OUTPUTS=$(gh run view $DEPLOYMENT_RUN_ID --json jobs -q ".jobs[0].steps[-1].outputs")

          ERD_WEB_URL=$(echo "$OUTPUTS" | jq -r '.erd-web-url')
          CLI_URL=$(echo "$OUTPUTS" | jq -r '.cli-url')

          echo "erd-web-url=$ERD_WEB_URL" >> $GITHUB_OUTPUT
          echo "cli-url=$CLI_URL" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  e2e-tests:
    needs: fetch-deployment-outputs
    uses: ./.github/workflows/_run_e2e_test.yml
    with:
      working-directory: 'frontend/packages/e2e'
      erd-web-url: ${{ needs.fetch-deployment-outputs.outputs.erd-web-url }}
      cli-url: ${{ needs.fetch-deployment-outputs.outputs.cli-url }}
