name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true
  WORKING_DIRECTORY: .

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-cli:
    uses: ./.github/workflows/_run_e2e_test.yml
    with:
      url: 'https://liam-erd-sample.vercel.app/'
      working-directory: 'frontend/packages/cli'

  test-erd-web:
    uses: ./.github/workflows/_run_e2e_test.yml
    with:
      url: 'https://liam-erd-web.vercel.app/erd/p/github.com/mastodon/mastodon/blob/main/db/schema.rb'
      working-directory: 'frontend/packages/erd-core'
