name: E2E Tests
on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  e2e-test:
    uses: ./.github/workflows/_run_e2e_test.yml
    with:
      url: ${{ inputs.url }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e-test
      cancel-in-progress: true
