name: E2E Tests
on:
  workflow_run:
    workflows:
      - "Vercel Deployment"
      - "Vercel Deployment erd-sample"
    types:
      - completed

env:
  CI: true
  WORKING_DIRECTORY: .

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-deployment-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment outputs
        run: |
          DEPLOYMENT_RUN_ID=${{ github.event.workflow_run.id }}
          OUTPUTS=$(gh run view $DEPLOYMENT_RUN_ID --json outputs -q ".outputs")

          ERD_WEB_URL=$(echo "$OUTPUTS" | jq -r '.erd-web-url')
          CLI_URL=$(echo "$OUTPUTS" | jq -r '.cli-url')

          echo "ERD_WEB_URL=$ERD_WEB_URL" >> $GITHUB_ENV
          echo "CLI_URL=$CLI_URL" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-cli:
    needs: [fetch-deployment-outputs]
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/_run_e2e_test.yml
    with:
      base-url: ${{ env.CLI_URL }}

  test-erd-web:
    needs: [fetch-deployment-outputs]
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/_run_e2e_test.yml
    with:
      base-url: ${{ env.ERD_WEB_URL }}
