name: E2E Tests

on:
  deployment_status:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, "Mobile Safari"]
      fail-fast: false
    defaults:
      run:
        working-directory: "frontend/packages/e2e"
    env:
      CI: true
      URL: ${{ github.event.deployment_status.target_url }}
      ENVIRONMENT: ${{ github.event.deployment.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.sha }}

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      # This workflow is triggered for all deployments (liam-app, liam-erd-sample, liam-docs),
      # but E2E tests are executed only for liam-app deployments now.
      - name: Run e2e tests
        if: |
          github.event_name == 'deployment_status' &&
          github.event.deployment_status.state == 'success' &&
          (
            (
              contains(github.event.deployment.environment, 'Production') &&
              contains(github.event.deployment_status.target_url, 'liam-app-git-main')
            ) ||
            (
              contains(github.event.deployment.environment, 'Preview') &&
              !contains(github.event.deployment_status.target_url, 'liam-erd-sample') &&
              !contains(github.event.deployment_status.target_url, 'liam-docs')
            )
          )
        run: pnpm exec playwright test --project="${{ matrix.browser }}"
        env:
          URL: ${{ env.URL }}
