name: E2E Tests

on:
  deployment_status:

jobs:
  e2e-tests:
    if: |
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success' &&
      (
        (
          contains(github.event.deployment.environment, 'Production') &&
          contains(github.event.deployment_status.target_url, 'liam-erd-web')
        ) ||
        (
          contains(github.event.deployment.environment, 'Preview') &&
          !contains(github.event.deployment_status.target_url, 'liam-erd-sample') &&
          !contains(github.event.deployment_status.target_url, 'liam-docs')
        )
      )
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, "Mobile Safari"]
      fail-fast: false
    defaults:
      run:
        working-directory: "frontend/packages/e2e"
    env:
      CI: true
      URL: ${{ github.event.deployment_status.target_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.sha }}

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps

      - name: Install system dependencies for WebKit
        # Some WebKit dependencies seem to lay outside the cache and will need to be installed separately
        if: ${{ steps.playwright-cache.outputs.cache-hit == 'true' }}
        run: pnpm exec playwright install-deps webkit

      - name: Run e2e tests
        run: pnpm exec playwright test --project="${{ matrix.browser }}"
        env:
          URL: ${{ github.event.deployment_status.target_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: frontend/packages/e2e/test-results/
          retention-days: 30

      - name: Slack Notification on Failure
        if: ${{ github.event.deployment.environment == 'production' && failure() }}
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
        with:
          text: "E2E Test Failure"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Browser",
                    "value": "${{ matrix.browser }}"
                  },
                  {
                    "title": "Result",
                    "value": "failure"
                  },
                  {
                    "title": "Job URL",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
