name: test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for actions/checkout, peter-evans/create-pull-request
  pull-requests: write # for peter-evans/create-pull-request

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: check @liam-hq/cli exit code
        shell: bash
        run: |
          version="0.3.5"
          if [ -z "${version}" ]; then
            echo "Error: Failed to extract version from package.json"
            exit 1
          fi
          docker run --rm node:22-bullseye npx --yes @liam-hq/cli@${version} --version