name: frontend-ci

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: read
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            has-changes:
              - '.github/workflows/frontend-ci.yml'
              - '.github/actions/pnpm-setup/**'
              - './frontend/**'

  frontend-windows-ci:
    needs: [setup-job]
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - run: npm install -g frontend/packages/cli/liam-hq-cli-0.4.1.tgz
      - run: liam erd build --input https://github.com/mastodon/mastodon/blob/v4.3.2/db/schema.rb --format schemarb
      - run: Get-ChildItem ./dist | Select-Object Name, CreationTime, LastWriteTime, Mode, Length
