name: frontend-ci

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: read
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            has-changes:
              - '.github/workflows/frontend-ci.yml'
              - '.github/actions/pnpm-setup/**'
              - './frontend/**'
              - '.syncpackrc'
              - 'biome.jsonc'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'turbo.json'

  frontend-lint:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup
      - run: pnpm lint

  frontend-ci:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup
      - run: pnpm --filter @liam-hq/db supabase:start
      - run: cp .env.template .env
      - run: ./scripts/extract-supabase-anon-key.sh
      - run: pnpm test:turbo
      - name: Check for diff in generated types
        run: |
          pnpm --filter @liam-hq/db supabase:gen
          git add frontend/packages/db/supabase/database.types.ts
          if ! git diff HEAD --ignore-space-at-eol --exit-code frontend/packages/db/supabase/database.types.ts; then
            echo "Generated types differ from committed file."
            git diff HEAD frontend/packages/db/supabase/database.types.ts
            exit 1
          else
            echo "Generated types are up-to-date."
            exit 0
          fi
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: migrations-changes
        with:
          filters: |
            has-changes:
              - '.github/workflows/frontend-ci.yml'
              - 'frontend/packages/db/schema'
              - 'frontend/packages/db/supabase/migrations'
      - name: Check schema.sql
        if: ${{ steps.migrations-changes.outputs.has-changes == 'true' }}
        run: |
          pnpm --filter @liam-hq/db schema:gen
          git add frontend/packages/db/schema/schema.sql
          if ! git diff HEAD --ignore-space-at-eol --exit-code -- frontend/packages/db/schema/schema.sql; then
            echo "schema.sql has changed. Review the changes."
            echo "Please run \`pnpm --filter @liam-hq/db schema:gen\` to update the file."
            exit 1
          else
            echo "schema.sql is up-to-date."
            exit 0
          fi
