name: Notify Supabase Failure

on:
  check_run:
    types: [completed]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.app.name == 'Supabase / Supabase Preview'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Slack Notification for Supabase Failure
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
        with:
          text: "Supabase Preview Deployment Failure"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Branch",
                    "value": "main"
                  },
                  {
                    "title": "Check Name",
                    "value": "${{ github.event.check_run.name }}"
                  },
                  {
                    "title": "Result",
                    "value": "failure"
                  },
                  {
                    "title": "Check Run URL",
                    "value": "${{ github.event.check_run.html_url }}"
                  }
                ]
              }
            ]
