name: release-debug
on:
  push:
    branches:
      - release-debug-branch
env:
  working-directory: frontend

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  create_release_pull_request_or_publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CI_TRIGGER_APP_ID }}
          private-key: ${{ secrets.CI_TRIGGER_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            ${{ env.working-directory }}
          token: ${{ steps.app-token.outputs.token }}

      - uses: ./.github/actions/pnpm-setup
        with:
          working-directory: ${{ env.working-directory }}

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.4.9
        with:
          cwd: ${{ env.working-directory }}
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
