name: release(investigation now)
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  working-directory: frontend

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  create_release_pull_request_or_publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CHANGESET_CI_TRIGGER_APP_ID }}
          private-key: ${{ secrets.CHANGESET_CI_TRIGGER_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          sparse-checkout: |
            .changeset
            .github
            ${{ env.working-directory }}
      - uses: ./.github/actions/pnpm-setup
        with:
          working-directory: ${{ env.working-directory }}
      - name: debug 1
        run: pnpm changeset version
        working-directory: ${{ env.working-directory }}
      - name: debug 2
        run: git status
        working-directory: ${{ env.working-directory }}
