# This workflow specifically deploys the `apps/erd-sample` and `apps/erd-web` app.
# For deployments of other `apps/*` apps, see `.github/workflows/vercel-deploy.yml`.
name: Vercel Deployment erd-sample

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      environment: ${{ steps.environment.outputs.environment }}
      has-changes: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/branch-names@v7.0.7
        id: branch-name
      - name: Detect Environment Changes
        id: environment
        run: |
          echo "environment=${{ steps.branch-name.outputs.current_branch == 'main' && 'production' || 'preview' }}" >> $GITHUB_OUTPUT
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - './.github/workflows/vercel-deploy-erd.yml'
              - './.github/workflows/_run_e2e_test.yml'
              - './frontend/apps/erd-sample/**'
              - './frontend/apps/erd-web/**'
              - './frontend/packages/cli/**'
              - './frontend/packages/db-structure/**'
              - './frontend/packages/e2e/**'
              - './frontend/packages/erd-core/**'
              - './frontend/packages/ui/**'
              - './pnpm-lock.yaml'

  deploy:
    name: Deploy
    needs: [setup-deployment]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ needs.setup-deployment.outputs.has-changes == 'true' }}
    strategy:
      matrix:
        apps:
          - name: "@liam-hq/erd-sample"
            vercel-project-id-key: VERCEL_PROJECT_ID_ERD_SAMPLE
          - name: erd-web
            vercel-project-id-key: VERCEL_PROJECT_ID_ERD_WEB
    environment:
      name: "${{ needs.setup-deployment.outputs.environment }} - ${{ matrix.apps.name }}"
    permissions:
      contents: read
      deployments: write
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Application
        id: deploy-app
        uses: ./.github/actions/deploy-app
        with:
          app-name: ${{ matrix.apps.name }}
          environment: ${{ needs.setup-deployment.outputs.environment }}
          vercel-project-id-key: ${{ matrix.apps.vercel-project-id-key }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

      - name: Store Deployment Data
        id: set-matrix
        run: |
          MATRIX=$(jq -c -n --arg name "${{ matrix.apps.name }}" --arg url "${{ steps.deploy-app.outputs.deployment-url }}" '[{name: $name, url: $url}]')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
        shell: bash

  run-e2e:
    needs: deploy
    if: needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.deploy.outputs.matrix) }}
    steps:
      - name: Run E2E Tests
        uses: ./.github/workflows/_run_e2e_test.yml
        with:
          app-name: ${{ matrix.app.name }}
          url: ${{ matrix.app.url }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-e2e
      cancel-in-progress: true
